version: '3.8'

services:
  postgres:
    image: postgres:15
    container_name: e-commerce-postgres
    restart: always
    environment:
      POSTGRES_USER: beytullahp
      POSTGRES_PASSWORD: beytullahpassword
      POSTGRES_DB: e-commerce-deneme
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  app:
    image: my-spring-ecommerce-app:latest
    container_name: e-commerce-app
    restart: always
    depends_on:
      - postgres
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/e-commerce-deneme
      SPRING_DATASOURCE_USERNAME: beytullahp
      SPRING_DATASOURCE_PASSWORD: beytullahpassword
    ports:
      - "8080:8080"

  frontend:
    image: my-react-ecommerce-app:latest
    container_name: e-commerce-frontend
    restart: always
    ports:
      - "3000:80"  # Nginx serves the app on port 80 inside container
    depends_on:
      - app

volumes:
  pgdata:
