version: '3.8'

services:
  postgres:
    image: postgres:15
    container_name: e-commerce-postgres
    restart: always
    environment:
      POSTGRES_USER: beytullahp
      POSTGRES_PASSWORD: beytullahpassword
      POSTGRES_DB: e-commerce-deneme
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
